version: 2
checks:
  method-lines:
    config:
      threshold: 45
  method-complexity:
    config:
      threshold: 10
  similar-code:
    enabled: false
plugins:
  eslint:
    enabled: true
    
excluded_patterns:
  - "docs/"
  - "types/"