root: true
parser: '@babel/eslint-parser'
parserOptions:
  ecmaFeatures:
    modules: true
  ecmaVersion: 6
  sourceType: module
extends:
  - '@wfcd/eslint-config/strict-esm-jsdoc'
  - 'plugin:redos/recommended'
rules:
  import/extensions:
    - error
    - ignorePackages
overrides:
  - rules:
      no-new: off
      'prefer-arrow-callback': off
      'func-names': off
      'no-unused-expressions': off
      'valid-jsdoc': off
      'import/no-extraneous-dependencies':
        - error
        - devDependencies: true
          optionalDependencies: false
          peerDependencies: false
      'no-console': off
    parserOptions:
      requireConfigFile: false
    env:
      mocha: true
    files:
      - './test/**/*.spec.js'
