root: true
parser: '@babel/eslint-parser'
parserOptions:
  ecmaFeatures:
    modules: true
  ecmaVersion: 6
  sourceType: module
extends:
  - '@wfcd/eslint-config/strict-esm-jsdoc'
  - 'plugin:redos/recommended'
rules:
  import/extensions:
    - error
    - ignorePackages
overrides:
  - rules:
      no-new: off
    files:
      - './test/**/*.spec.js'