name: Exercise (npm)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Lint
      run: |
        npm ci
        npm run lint
      env:
        CI: true
    - name: Test
      run: |
        npm ci
        npm test
      env:
        CI: true
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
          github-token: ${{ secrets.github_token }}
          parallel: true
          path-to-lcov: ./coverage/lcov.info

    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      with:
        branch: master
        dry_run: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

